### ISSUE TITLE
Remove mvn-source-plugin from the lifecycle?

### ISSUE THREAD

**Issue by Sanrag** [sladeware/groningen#5]
It really slows down the build. Is it there for any particular reason?

If you're OK with removing it, assign the issue back to me and I can go ahead and do it.

**Comment by matttproud** [comment]
If you're OK with it, let me study the configuration and get back to you.
Am 17.08.2013 00:10 schrieb "Sanrag Sood" notifications@github.com:

**Comment by matttproud-soundcloud** [comment]
Here's the use of it:
1. We are going to try to get our built artifacts into a public Maven repository.  (I went ahead and took care of getting permission last month.)
2. If we submit our artifacts, we should be good citizens for folks who may build against them.  To do this, including Javadoc and Source JAR artifacts is polite.  This step is responsible for building those.

What are your thoughts?

**Comment by Sanrag** [comment]
Ah, I didn't know about that. Thanks for explaining.

On Sat Aug 17 2013 at 3:36:45 AM, Matt T. Proud notifications@github.com
wrote:

Here's the use of it:

   1.

   We are going to try to get our built artifacts into a public Maven
   repository. (I went ahead and took care of getting permission last month.)
   2.

   If we submit our artifacts, we should be good citizens for folks who may
   build against them. To do this, including Javadoc and Source JAR artifacts
   is polite. This step is responsible for building those.

What are your thoughts?

—
Reply to this email directly or view it on
GitHubhttps://github.com/sladeware/groningen/issues/5#issuecomment-22809421
.

**Comment by Sanrag** [comment]
Surprisingly, it takes way more time on my linux box (~20 minutes) than on Macbook Air (~5 minutes) even though the Linux box has a much better configuration
